### PR TITLE
Throttling logic for write_gcm. 

### PR DESCRIPTION
**Pull request by coreykosak**
write_gcm keeps a running estimate of how much memory the upstream
server is using for key storage. If this estimate
reaches a high water mark, then the sending of "detail"-type keys is
suppressed until the estimate reaches a low water mark. The rationale is
that there are some scenarios/configurations where the processes plugin
might spam the server with too much data.

### CODE REVIEW

**Comment by coreykosak** [comment]
I tested this a fair amount. Seems to be working pretty well.

**Comment by katzj** [comment]
Diff is too much in one file for github to be happy :(  

My main thought is does this make sense to live in the output plugin?  Generally, output plugins don't know anything about specific input plugins and instead are just writing out things from the cache.

**Comment by coreykosak** [comment]
You should be able to see the diff in a client-side tool like gitk. Are you able to do that? If not, what would you like me to do?

Regarding your second question, I've been debating that question myself. As you can see from the change, the write_gcm plugin does indeed have to have some plugin knowledge baked into it, in order to figure out what to drop in the red alert scenario. So I agree this is awkward.

But in the alternative scenario, I don't think it belongs in the input plugin either, for symmetric reasons. Why should the processes plugin have to know that our Monarch server has memory limitations and that it should start throttling itself at a certain point? The processes plugin doesn't even know that it's connected to write_gcm obviously.

Maybe the right solution is to do this with a filter?

**Comment by katzj** [comment]
Yeah, I looked with git locally.  It just makes it harder to do any sort of line-by-line review.

A filter sounds like it would work and might be the best way to do it, although it might be a little ugly to write

**Pull request merged**
