### PR TITLE
Change JSON support so that it is backwards compatible with libyajl-1.0.7

### PR DESCRIPTION
**Pull request by coreykosak**
So it seems that my libyajl 1.0.10 support wasn't good enough because (I think) 1.0.7 is what is in the RHEL6 repository.

So I rewrote my code to be 1.0.7-compliant.

I think this should work on all versions (tested on Debian wheezy and RHEL6)

### CODE REVIEW

**Comment by katzj** [comment]
lgtm

**Comment by katzj** [comment]
I don't have a yajl_version.h in my yajl.  I think we need to do like is done in curl_json.c, etc where it checks to see if HAVE_YAJL_VERSION_H before doing the include

**Comment by kosak** [comment]
That is great. I was looking exactly for a solution like this last night. Thanks!

**Comment by coreykosak** [comment]
fix committed to repo

**Pull request merged**
