### PR TITLE
Add support for Application Default Credentials.

### PR DESCRIPTION
**Pull request by coreykosak**

### CODE REVIEW

**Comment by coreykosak** [comment]
Tested on AWS Ubuntu 14. Things _seemed_ to work really well (happy result from the server) but I saw no results in pcon-test. Do I perhaps have to do something to make my GCP project aware of my AWS VM?

Here's an example JSON message from AWS:
```
{"name":"project/sd-sandbox-1","resource":{"type":"aws_ec2_instance","labels":{"region":"aws:us-east-1","instance_id":"i-855a8c3b","aws_account":"032939080721"}},"collectdVersion":"stackdriver_agent/kosak2000","collectdPayloads":[{"startTime":{"seconds":1447222457,"nanos":383291378},"endTime":{"seconds":1447222457,"nanos":383291378},"plugin":"df","pluginInstance":"none","type":"df_complex","typeInstance":"free","values":[{"dataSourceType":"gauge","dataSourceName":"value","value":{"doubleValue":"104853504.000000"}}]},{"startTime":{"seconds":1447222457,"nanos":383292338},"endTime":{"seconds":1447222457,"nanos":383292338},"plugin":"df","pluginInstance":"none","type":"df_complex","typeInstance":"reserved","values":[{"dataSourceType":"gauge","dataSourceName":"value","value":{"doubleValue":"0.000000"}}]},{"startTime":{"seconds":1447222457,"nanos":383293567},"endTime":{"seconds":1447222457,"nanos":383293567},"plugin":"df","pluginInstance":"none","type":"df_complex","typeInstance":"used","values":[{"dataSourceType":"gauge","dataSourceName":"value","value":{"doubleValue":"4096.000000"}}]}]}
```

**Comment by katzj** [comment]
I think we worked through why you didn't see the data earlier today.  Let me know if you still need a link.

This generally looks good, although unless I'm missing something, this just has the support for the new-style json creds and not the default paths for application default creds?   I think the order is
1) If something is explicitly specified in the config file, use it
2) Try to use the instance scope if on gce
3) Try to use /etc/google/auth/application_default_credentials.json (json creds)
4) Try to use /root/.config/gcloud/application_default_credentials.json (json creds)
5) Throw an error that we have no way to get creds 

Also, we should be able to extract the project number from the client email (though it's now two different regexes instead of one) so that aws users don't have to manually specify that either.

**Comment by kosak** [comment]
Ah, OK I need to pick this back up and finish it. Is your 1-5 strictly correct (to the point where I can just implement it as stated) or is there some nice Google documentation somewhere I should read instead?

**Comment by mr-salty** [comment]
The docs are: https://developers.google.com/identity/protocols/application-default-credentials

What Jeremy said is mostly correct aside from the order, which should be:

1) The path specified by the environment variable $GOOGLE_APPLICATION_CREDENTIALS
2) The user default path.
3) The system default path.
4) Use the GCE service account credentials.

(2) is $HOME/.config/gcloud/application_default_credentials.json (where $HOME shoud be /root), for windows it uses %APPDATA% rather than home

Note that (3) is not yet documented externally but it has been accepted by the team that works on it and is implemented/released in ruby (https://github.com/google/google-auth-library-ruby/pull/33).  For unix the path is /etc/google/auth and for windows it is %ProgramData%\Google\Auth (the filename is application_default_credentials.json in both cases)

I explicitly decided *not* to provide an option to set the credentials path in the config file for fluentd, since it is non-standard and there are already multiple options available to the user.

**Comment by coreykosak** [comment]
Ah beautiful. Thanks for the info!

**Comment by katzj** [comment]
Pulled this into #49 and then merged it

**Pull request closed without merging**
