### PR TITLE
write_gcm redone

### PR DESCRIPTION
**Pull request by coreykosak**
Hi Jeremy,

This is the new version of write_gcm. I ultimately didn't like the approach I used in https://github.com/Stackdriver/collectd/pull/22 because it was hard to read and might have a tendency towards being racy.

The key idea behind this new version is that there is a single thread dedicated to processing points and uploading them to the server. Thanks to that, wg_write and wg_flush are extremely simple... all they need to do is append their value to a queue and then they're done. But as a consequence, the single thread that writes the points is also "simple". I mean, unfortunately it has a lot to do, but at least it's a fairly straightforward set of operations.

Let me know what you think!

### CODE REVIEW

**Comment by katzj** [comment]
Okay, diff is too large to be rendered.  Going to try to give some useful comments here but if things aren't clear, holler.  Some of them aren't blockers to getting merged and moving along as far as I'm concerned but are "we should do them before we call things done".  

* Lost the copyright header at the top.  That's important to keep :)
* Obviously the endpoint format string should be updated to point to the prod api.  I think it makes more sense to have an option to override the endpoint so that we can point to test or locally with a config change but the default behavior of the plugin points to the prod endpoint.  
* Some of the INFO look more like DEBUG.  I don't think this really blocks us merging it.
* It looks like you changed things to only work with yajl2?  Some (most I think) of the Linux distros we support right now only ship yajl 1.x.  I think we'll break the build as it stands, so need to do something here.  Note that "do something" could mean that we turn off building of write_gcm for distros without yajl2 and then fix in a follow-on.
* For all of the json writing, is there a reason to do it with bespoke hand-crafted string formatting vs just throwing it at yajl and having it do it for us?  
* In the config, it looks like you can specify project + instance but I think you also need to be able to specify location for uniquely qualifying an instance.  And it probably also needs to have provider (gce only right now).  I'm okay doing this as a follow on, so not a blocker to merge.
* We can do it as a follow-on, but we should make it so that we can support the [application default credentials json file](https://developers.google.com/identity/protocols/application-default-credentials) instead of or in addition to email+p12 file+secret.  Not a blocker to merge.

**Comment by coreykosak** [comment]
Are you telling me that yajl can generate JSON? HAHAHAH oops, didn't realize that. I thought it was just a parser. I can change that :)

**Comment by coreykosak** [comment]
You know that special thing where github won't show diffs because there are "too many" of them? Well, that happened again. Note: it's "too many" because it's 1985 and you're obviously browsing this with your Apple ][.

Anyway the above change builds but I haven't yet had the energy to test it. I wanted to give you an advance look of the changes though. Change summary:
1. Copyright: done
2. Endpoint string: done. (see e.g. line 1365) _**PLEASE TELL ME WHAT THE PROD ENDPOINT URL IS*__
3. INFO changed to DEBUG. done
4. yajlv1: _**NOT**_ done.
5. json writing: changed to imperative style and handing off to yajl. Still using my "check errors only at the end" technique because I _refuse_ to put an 'if' statement after every single call to yajl_gen_string. _By the way_ the fact that I have little wrapper functions for all the json emitting (see e.g. wg_json_string at line 1726) means that it will "probably" be easier for the code to support either v2 or v1 because the json is abstracted away.
6. Specifying provider and location: done. See wg_configbuilder_create at line 1030. Can now specify aws or gcp (although talking to the aws metadata server isn't there yet). Ultimately the info is digested into a "monitored_resource_t" (see lines 1129-1148)
7. Application default credentials: not done.

**Comment by katzj** [comment]
* Prod endpoint is https://monitoring.googleapis.com/v3/%s/collectd/timeSeries from looking at the discovery doc.
* Let's just go with yajlv2 only for now and turn off building write_gcm on distros that don't have v2.  That'll let me install on an instance or two and then we can get in switching between yajl versions

**Comment by coreykosak** [comment]
PTAL. This version seems to actually work, _**EXCEPT**_ for the prod URL, which 404's for me, both from the plugin and from my browser when I just try to navigate to it (substituting some project name for the %s).

**Comment by coreykosak** [comment]
Ah, speak of the devil. http://cl/105603762 it's now /v3/projects/<project_id>/collectdTimeSeries

(which is probably not up yet either). Hold for change.

**Comment by katzj** [comment]
One tiny merge conflict but from there, I say we merge it and we can iterate from here

**Comment by katzj** [comment]
:shipit:

**Comment by coreykosak** [comment]
Rebased (didn't merge) stackdriver-agent-5.5.0 to squashed version of this PR.

**Pull request closed without merging**
