### PR TITLE
Varnish 5.2 compatibility changes taken from collectd#2527

### PR DESCRIPTION
**Pull request by gbprz**
This contains cherry picked commits from collectd#2527. While working on the build for Ubuntu Bionic, I noticed there are no packages available for libvarnishapi-dev versions lower than 5.2. Pulling in Xenial sources seemed like an incorrect approach. 

**Note**: the build script will need to be run since this makes changes to the autoconf configure script. I have a few open branches for required Bionic build changes and at least one of them also requires running the build script. To avoid merge conflicts, I left this commit out of this PR until everything is merged into the "gabeperez-bionic-build-changes" feature branch. My idea was to run the build script once everything is merged into that branch. Please let me know if you would prefer I include this commit instead.

### CODE REVIEW

**Review by igorpeshansky — APPROVED** [review]
LGTM :shipit:

**Review by davidbtucker — APPROVED** [review]
LGTM

**Comment by gbprz** [comment]
All set, checks are passing now

**Comment by igorpeshansky** [comment]
This is a cherrypick of upstream commits.

**Comment by viable-hartman** [comment]
Did this actually get merged?  I'm running Varnish 5.2 and have the 5.5.2-384 stack driver installed, but the varnish.so library still says:

varnish.so: /lib64/libvarnishapi.so.1: version `LIBVARNISHAPI_1.0' not found (required by /opt/stackdriver/collectd/lib64/collectd/varnish.so)

...and won't load the varnish plugin.

**Comment by igorpeshansky** [comment]
@viable-hartman, this should be merged. Could you please open a new issue and mention the Linux distro where you're experiencing this? Also, the output of `ldd /opt/stackdriver/collectd/lib64/collectd/varnish.so` would help. Thanks!

**Pull request merged**
