### PR TITLE
Fix potential buffer overrun error from #173.

### PR DESCRIPTION
**Pull request by igorpeshansky**

### CODE REVIEW

**Review by davidbtucker — APPROVED** [review]
Thanks!

**Comment by jkohen** [comment]
Thank you! These APIs are bad :(

**Review by jkohen — APPROVED** [review]

**Comment by igorpeshansky** [comment]
Re: "these APIs are bad", WDYT about [my suggestion of `read_text_file_contents`](https://github.com/Stackdriver/collectd/pull/171#issuecomment-567110183)?..

**Comment by jkohen** [comment]
Resounding LGTM, Igor.

**Comment by igorpeshansky** [comment]
Sent collectd/collectd#3359.

**Pull request merged**
