### PR TITLE
Kosak 5.4.2 candidate

### PR DESCRIPTION
**Pull request by coreykosak**

### CODE REVIEW

**Comment by katzj** [comment]
Ugh, this is a hard one.  I wonder if it'd be easier to review if we were applying our changes on top of 5.4.2 instead of the other way around? 

I can't even view it in the github diff viewer without it crashing my browser :(

**Comment by coreykosak** [comment]
OK, first, here's a nickel. Go install Chrome instead of whatever POS browser you are using now.

Second, are you saying the result would look different if I did the merge in the other direction? I guess I could try that.  (Maybe I did it in the suboptimal direction. I kind of hate the "merge" workflow anyway and it's very hard to analyze the project history. I'd much rather live in a "rebase" world than a "merge" world. But anyway maybe it's too late to have those kinds of discussions).

**Comment by peaton** [comment]
coreykosak, lol.

**Comment by coreykosak** [comment]
Heh heh.

Anyway, I'd like to be clear about the merge. I basically did a merge between the two branches, and manually resolved a dozen or so merge conflicts spread over maybe 5-10 files. This pull request may look like it touches lots of commits (and it does) but I certainly didn't touch more than a handful of things when doing the merge.

**Comment by coreykosak** [comment]
P.S. I'm also fine with Firefox :smile:

**Comment by coreykosak** [comment]
I'm going to close this PR (without merging) as it's been mooted by https://github.com/Stackdriver/collectd/pull/18

**Pull request closed without merging**
