### PR TITLE
Kosak sd 5.5.0 candidate - version 2

### PR DESCRIPTION
**Pull request by coreykosak**

### CODE REVIEW

**Comment by coreykosak** [comment]
You had asked me to cherry-pick a commit for https://github.com/Stackdriver/collectd/pull/18. I decided instead to rebase against the latest SD head. Somehow I messed up https://github.com/Stackdriver/collectd/pull/18 so I just decided to redo it here. Please take a look.

**Comment by coreykosak** [comment]
Please take another look, particularly at https://github.com/Stackdriver/collectd/commit/d8589180f7411197db955f59e0d11d2a24bab107

**Comment by katzj** [comment]
lgtm at this point.

**Comment by coreykosak** [comment]
OK. I am going to "accept" this Pull Request by creating the new branch stackdriver-agent-5.5.0. (There will be no merge).

**Pull request closed without merging**
