### PR TITLE
Fix mongoc header and update write_mongodb.c from upstream.

### PR DESCRIPTION
**Pull request by luna391**

### CODE REVIEW

**Comment by luna391** [comment]
I signed it!

**Comment by luna391** [comment]
@nina-marie @gbprz can any of you review this PR.
I'm working on packaging stackdriver for nixos and this is a blokcer for us. 
Thanks for your time and help.

**Comment by igorpeshansky** [comment]
@luna391, can you please elaborate your use case? Stackdriver currently does not support nixos. What configure options are you using to build? Did you test this change on the existing platforms to make sure it doesn't break?

**Comment by luna391** [comment]
@igorpeshansky thanks for the quick follow-up. 
We're working on packaging Stackdriver to be working on NixOS. 
We have GCP instances running on NixOS and we wanted to start collecting disk usage, memory usage ... which can't be accomplished without Stackdriver agent being installed. 
The Stackdriver packaging is inspired from collectd packaging, for further details: 
https://github.com/NixOS/nixpkgs/tree/master/pkgs/tools/system/collectd
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/monitoring/collectd.nix

Now regarding the issue we faced while using the "stackdriver-agent-5.5.2" code, while we're compiling an error is thrown: *src/write_mongodb.c* file is including a header that does not exist which is *mongo.h* 

`write_mongodb.c:42:10: fatal error: mongo.h: No such file or directory
 #include <mongo.h>
          ^~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:4970: write_mongodb_la-write_mongodb.lo] Error 1` 

Checking the code, we found that there's no *mongo.h* file and there's only the "mongoc.h" header and that's why we tried to fix it. 
As you can see in the code that exists in "5.8.1" branch the correct header name is being used, line 39: `#include <mongoc.h>
`
https://github.com/Stackdriver/collectd/blob/collectd-5.8.1/src/write_mongodb.c

Please let me know if you need further details. 
Thanks,

**Comment by igorpeshansky** [comment]
Ah, I see now. We don't bundle the `write_mongodb` plugin into our packages, so never noticed that it's broken. Do you actually *need* `write_mongodb`, or are you simply after a NixOS equivalent of the official Stackdriver package? Note that our packages are built using the recipes in [Stackdriver/agent-packaging](https://github.com/Stackdriver/agent-packaging) —  you might want to emulate those (especially the configure options) on NixOS.
Also note that on newer OS versions (e.g., Ubuntu 18.04) we are using `--with-libmongoc=yes` instead of `--with-libmongoc=own`, to avoid the (also broken) vendored version of libmongoc.

**Comment by luna391** [comment]
@igorpeshansky, we're working to get a NixOS equivalent of the official Stackdriver package. 
I'll check the recipes in Stackdriver/agent-packaging .That being said, can we merge this PR to fix the write_mongodb plugin ? 
thanks.

**Review by igorpeshansky — APPROVED** [review]
Yes, we can merge it, but there are no guarantees that `write_mongodb` actually works in our fork, since we've never actually built it, let alone tested it. Is this the only change that's required to build on NixOS?

**Comment by luna391** [comment]
@igorpeshansky we're currently testing the NixOS packaging, for now build succeeded but we're not able to see that metrics are being sent from GCP instances. 
I found other issues in write_mongodb.c file so I've copied the one used in collectd-5.8.1 branch, that made our build succeed. So you might check the changes pushed as part of your PR and if you have issues please raise them.
Thanks !

**Comment by igorpeshansky** [comment]
As I said before, I wouldn't expect `write_mongodb` to work or build at all, so rather than trying to fix it, I'd suggest abandoning this PR and simply not enabling it in your packaging. I'm wary of pulling in changes from the `collectd-5.8.1` branch into `stackdriver-agent-5.5.2` — we're working on a separate rebase against 5.8.1 that will eventually supersede this branch.

**Review by igorpeshansky — CHANGES_REQUESTED** [review]
See above.

**Comment by luna391** [comment]
@igorpeshansky we finally were able to package Stackdriver on NixOS, the missing part was related to the configuration once we've fixed it we were able to install the agent and start sending the needed metrics. 
We've used the code in this PR: src/write_mongodb.c , that was the only needed update we need to push to stackdriver-agent-5.5.2. 
Thus if it's possible to merge this PR to fix the broken src/write_mongodb.c since you're not using any ways in your packaging but it's currently being used in ours and the updated version is working fine. 
Please let me know what do you think. 
Thanks,

**Review by igorpeshansky — APPROVED** [review]
FYI, I've tested this on SLES12, and our build succeeds from this branch. I don't see any harm in this, and it shouldn't adversely affect our rebase. I'll merge it now (@nina-marie FYI).

**Pull request merged**
