### PR TITLE
Rewrite mongodb.c to support MongoDB 3.0 (by using new driver)

### PR DESCRIPTION
**Pull request by coreykosak**
Tested on GCE on Debian Jessie and the latest MongoDB.

I wasn't 100% sure how to do the GNU auto* stuff, but I tried.

In one particular case ( https://github.com/Stackdriver/collectd/commit/93b514ba8200b96d8b233aa330cb1aed3d299a06 ) , I didn't know how to disable the tests in this subconfiguration, so I just hacked Makefile.am.

### CODE REVIEW

**Comment by coreykosak** [comment]
OK, picking this back up.

The ```mongodb.json``` file you sent me offline lists 18 metrics. I was already sending 17 of them. As of this change, I'm now sending all 18 (the missing one being ```global_lock_held```).

PTAL :fire_engine: :electric_plug: :family: :gb:

**Comment by coreykosak** [comment]
One more thing: ```global_lock_held``` is pretty hard to test because I believe the new versions of Mongo try hard not to take a global lock. I haven't been able to induce the server to actually generate a value for this, but I do believe I'm looking for it correctly :cry: :sob: :disappointed_relieved: :disappointed: :person_frowning: :smirk_cat:

**Comment by katzj** [comment]
lgtm

**Comment by coreykosak** [comment]
Here's where we are. I have tested this on Debian Jessie and RHEL7 (both on GCE). It seems to work, subject to the fact that some Stackdriver stuff is actually not apparently working right now.

(For example, I am transmitting connection counts and I see them in pcon, but I don't see them on the Stackdriver dashboard even though I see other metrics).

(Those connection counts aren't showing up even with the production agent).

Releasing this also depends on releasing the package changes in https://github.com/Stackdriver/agent-rpm/pull/46

**Comment by coreykosak** [comment]
I also had to change the code for ```global_lock_held``` because it changed in 3.0 and it changed again in 3.2. The current code should handle all cases: pre-3.0, 3.0, and 3.2.

**Comment by CaptainPatate** [comment]
Hi there,

Do you have a date for a Stackdriver release that will integrate this branch?

Cheers

**Comment by kosak** [comment]
We have a version that seems to work fine in all configurations except RHEL6.

The issue on RHEL6 is that the mongoc driver needs libbson, and libbson depends on libyajl2, but  the RHEL6 package repository provides libyajl1.

We'd like to provide a solution that works for RHEL6 users without breaking anyone who happens to depend on libyajl1.

I am not a master of Linux shared libraries, alas, and so I'm not 100% sure the best way to resolve this. There's a couple of things I still want to try. Maybe if we include the libyajl2 library in our Stackdriver shared library directory we can reference it without breaking everyone else.

This is however currently my second highest priority item, after getting an Ubuntu Xenial release done.

**Comment by coreykosak** [comment]
Hello @CaptainPatate,

We have a version of this in beta that has been working well in our own testing. Before releasing it more broadly, we would love the opportunity to test it in a couple of customer environments.

Would you be willing to be a beta tester for the new version of our agent? If so I would arrange to deliver a .deb or .rpm file to you appropriate to your platform. As always there is a small risk that something can go wrong, so I think this only makes sense if you have a non-production environment you can try it in.

Kindly contact me at kosak at google if you are interested. Thanks!

**Comment by coreykosak** [comment]
The new MongoDB agent has been pushed to production. Thanks @CaptainPatate for your help.

**Pull request closed without merging**
