### PR TITLE
New head branch: stackdriver-agent-5.5.2

### PR DESCRIPTION
**Pull request by coreykosak**
This is the result of squashing and rebasing all of our modifications onto the upstream head (fetched
as of today).

As discussed in https://docs.google.com/a/google.com/document/d/1Y9ZwvRYKLXgUG9Fr29gma3uMPcULrISwmjNj1rYWjYk/edit?usp=sharing , we decided that this was the best way to move to a new upstream branch (rather than merging or whatnot). Namely, simply abandoning stackdriver-agent-5.5.0 and starting a new stackdriver-agent-5.5.2

~~Note that due to the squashing and reorging, this branch does NOT have the property that every individual commit compiles cleanly.~~

~~(Of course it compiles cleanly at head).~~

### CODE REVIEW

**Comment by coreykosak** [comment]
Hi, please take another look. This is the version I'd like to submit, and cut our builds over to 5.5.2

Tested on {Apache, MongoDB, MySQL} x {RHEL6, RHEL7, Debian Jessie, Ubuntu Xenial} via Jenkins build number 335.

https://screenshot.googleplex.com/d8hH3Lsyyq2.png
https://screenshot.googleplex.com/89T6ydSomfT.png
https://screenshot.googleplex.com/NesG4nCAeC1.png

**Comment by katzj** [comment]
I haven't extensively read through all the commits but this looks reasonable to me.  I don't see anything obviously missing and the squashing ordering seems to make sense.  :shipit:

**Comment by igorpeshansky** [comment]
I'm also happy with this. :shipit:

**Comment by igorpeshansky** [comment]
This is now the default branch.

**Pull request closed without merging**
